---
title: "AAPrev Placenta"
author: "KC"
date: "5/7/2021"
output: html_document
---

AAPrev for protein (Empiria) and transcripts

data: total-tides.csv

# Protein

```{r, echo=FALSE, message=FALSE, warning=FALSE, out.width="50%"}

library(readxl)
bo <- read_excel("/Users/kcarpio/Desktop/boo.xlsx")

bo$Tissue <- as.factor(bo$Tissue)
bo$BabySex <- as.factor(bo$BabySex)
bo$Sample <- as.factor(bo$Sample)

library(lme4)
library(lmerTest)
library(ggplot2)

# Placental phthalates

qplot(AAPrev_lnp, PPARg.empl, data=bo, color = Sample, linetype = BabySex,geom='point') +  
  geom_smooth(aes(group=interaction(BabySex)), method = "lm", color = "black", size = 0.7) + facet_grid(.~Tissue)+theme_minimal() + ggtitle("PPARg")+ theme(axis.title.x = element_blank(), axis.title.y = element_blank()) + theme(plot.title = element_text(face = "bold")) +  theme(axis.text = element_text(size = 10)) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank())+
  theme(legend.text = element_text(size=10, 
                                   face="bold"))+
  theme(legend.title = element_text(size=10, 
                                    face="bold")) +
  scale_linetype_discrete(name="Fetal\nSex",
                          breaks=c("1", "2"),
                          labels=c("Male", "Female"))+ ylim(2.5, 10) +
  theme(plot.title = element_text(face = "bold"), axis.text.x = element_text(size=10, face="bold", colour = "black"), axis.text.y = element_text(size=10, face="bold", colour = "black"), strip.text.x = element_blank(), axis.line.y = element_line(), axis.line.x = element_line(), axis.ticks = element_line()) +
  guides(linetype=guide_legend("Fetal Sex"), color = FALSE)
  

qplot(AAPrev_lnp, hCGa.empl, data=bo, color = Sample, linetype = BabySex,geom='point') +  
  geom_smooth(aes(group=interaction(BabySex)), method = "lm", color = "black", size = 0.7) + facet_grid(.~Tissue)+theme_minimal() + ggtitle("hCGa")+ theme(axis.title.x = element_blank(), axis.title.y = element_blank()) + theme(plot.title = element_text(face = "bold")) +  theme(axis.text = element_text(size = 10)) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank())+
  theme(legend.text = element_text(size=10, 
                                   face="bold"))+
  theme(legend.title = element_text(size=10, 
                                    face="bold")) +
  scale_linetype_discrete(name="Fetal\nSex",
                          breaks=c("1", "2"),
                          labels=c("Male", "Female"))+
  theme(plot.title = element_text(face = "bold"), axis.text.x = element_text(size=10, face="bold", colour = "black"), axis.text.y = element_text(size=10, face="bold", colour = "black"), strip.text.x = element_blank(), axis.line.y = element_line(), axis.line.x = element_line(), axis.ticks = element_line(), legend.position = "top", legend.title = element_blank()) +
  guides(linetype=guide_legend("Fetal\nSex"), color = FALSE) +
  theme(panel.spacing = unit(1, "lines")) + ylim(2.5, 10)
  

qplot(AAPrev_lnp, hCGb.empl, data=bo, color = Sample, linetype = BabySex,geom='point') +  
  geom_smooth(aes(group=interaction(BabySex)), method = "lm", color = "black" , size = 0.7) + 
  facet_grid(.~Tissue)+theme_bw() + ggtitle("hCGb") + 
  theme(axis.title.x = element_blank(), axis.title.y = element_blank()) + 
  theme(plot.title = element_text(face = "bold"), axis.text.x = element_text(size=10, face="bold", colour = "black"), axis.text.y = element_text(size=10, face="bold", colour = "black"), strip.text.x = element_blank()) + 
  ylim(2.5, 10) + guides(linetype=guide_legend("Fetal Sex"), color = FALSE) + 
  theme(legend.text = element_text(size=10, 
                                   face="bold"))+
  theme(legend.title = element_text(size=10, 
                                    face="bold")) +
  scale_linetype_discrete(name="Fetal\nSex",
                          breaks=c("1", "2"),
                          labels=c("Male", "Female"))

```

# Transcripts

```{r echo=FALSE, message=FALSE, warning=FALSE, out.width="50%"}

library(readxl)
bo <- read_excel("/Users/kcarpio/Desktop/boo.xlsx")

bo$Tissue <- as.factor(bo$Tissue)
bo$BabySex <- as.factor(bo$BabySex)
bo$Sample <- as.factor(bo$Sample)

library(lme4)
library(lmerTest)
library(ggplot2)

# First trimester urinary

qplot(AAPrev_lnp, CGA.n, data=bo, color = Sample, linetype = BabySex,geom='point') +  
  geom_smooth(aes(group=interaction(BabySex)), method = "lm", color = "black" , size = 0.7) + 
  facet_grid(.~Tissue)+theme_bw() + ggtitle("CGA") + 
  theme(axis.title.x = element_blank(), axis.title.y = element_blank()) + 
  theme(plot.title = element_text(face = "bold"), axis.text.x = element_text(size=10, face="bold", colour = "black"), axis.text.y = element_text(size=10, face="bold", colour = "black"), strip.text.x = element_blank()) + 
  ylim(-0.55, 2) + guides(linetype=guide_legend("Fetal Sex"), color = FALSE) + 
  theme(legend.text = element_text(size=10, 
                                   face="bold"))+
  theme(legend.title = element_text(size=10, 
                                    face="bold")) +
  scale_linetype_discrete(name="Fetal\nSex",
                          breaks=c("1", "2"),
                          labels=c("Male", "Female"))+
  theme(axis.text = element_text(size = 10)) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA))+
  theme(panel.spacing = unit(1, "lines"))



qplot(AAPrev_lnp, CGA.n, data=bo, color = Sample, linetype = BabySex,geom='point') +  
  geom_smooth(aes(group=interaction(BabySex)), method = "lm", color = "black" , size = 0.7) + 
  facet_grid(.~Tissue)+theme_bw() + ggtitle("CGB") + 
  theme(axis.title.x = element_blank(), axis.title.y = element_blank()) + 
  theme(plot.title = element_text(face = "bold"), axis.text.x = element_text(size=10, face="bold", colour = "black"), axis.text.y = element_text(size=10, face="bold", colour = "black"), strip.text.x = element_blank()) + 
  ylim(-0.55, 2) + guides(linetype=guide_legend("Fetal Sex"), color = FALSE) + 
  theme(legend.text = element_text(size=10, 
                                   face="bold"))+
  theme(legend.title = element_text(size=10, 
                                    face="bold")) +
  scale_linetype_discrete(name="Fetal\nSex",
                          breaks=c("1", "2"),
                          labels=c("Male", "Female"))+
  theme(axis.text = element_text(size = 10)) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA))+
  theme(panel.spacing = unit(1, "lines"))


qplot(AAPrev_lnp, SNORA46.SDHA, data=bo, color = Sample, linetype = BabySex,geom='point') +  
  geom_smooth(aes(group=interaction(BabySex)), method = "lm", color = "black" , size = 0.7) + 
  facet_grid(.~Tissue)+theme_bw() + ggtitle("SNORA46") + 
  theme(axis.title.x = element_blank(), axis.title.y = element_blank()) + 
  theme(plot.title = element_text(face = "bold"), axis.text.x = element_text(size=10, face="bold", colour = "black"), axis.text.y = element_text(size=10, face="bold", colour = "black"), strip.text.x = element_blank()) + 
  ylim(-1, 1) + guides(linetype=guide_legend("Fetal Sex"), color = FALSE) + 
  theme(legend.text = element_text(size=10, 
                                   face="bold"))+
  theme(legend.title = element_text(size=10, 
                                    face="bold")) +
  scale_linetype_discrete(name="Fetal\nSex",
                          breaks=c("1", "2"),
                          labels=c("Male", "Female"))+
  theme(axis.text = element_text(size = 10)) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA))

qplot(AAPrev_lnp, PPARg.SDHA, data=bo, color = Sample, linetype = BabySex,geom='point') +  
  geom_smooth(aes(group=interaction(BabySex)), method = "lm", color = "black" , size = 0.7) + 
  facet_grid(.~Tissue)+theme_bw() + ggtitle("PPARg") + 
  theme(axis.title.x = element_blank(), axis.title.y = element_blank()) + 
  theme(plot.title = element_text(face = "bold"), axis.text.x = element_text(size=10, face="bold", colour = "black"), axis.text.y = element_text(size=10, face="bold", colour = "black"), strip.text.x = element_blank()) + 
  ylim(-1, 1) + guides(linetype=guide_legend("Fetal Sex"), color = FALSE) + 
  theme(legend.text = element_text(size=10, 
                                   face="bold"))+
  theme(legend.title = element_text(size=10, 
                                    face="bold")) +
  scale_linetype_discrete(name="Fetal\nSex",
                          breaks=c("1", "2"),
                          labels=c("Male", "Female"))+
  theme(axis.text = element_text(size = 10)) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA))


```
